### ISSUE TITLE
On importing ... opening db: 'burp-hash.sqlite': Access is denied

### ISSUE THREAD

**Issue by freeandnull** [burp-hash/burp-hash#4]
I'm on Windows 7 and it crashes on loading the extension:

`java.lang.NullPointerException
    at burp.Database.verify(Unknown Source)
    at burp.BurpExtender.loadDatabase(Unknown Source)
    at burp.BurpExtender.registerExtenderCallbacks(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at burp.xz.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
`

I watched using Process Monitor and found it's trying to create 'burp-hash.sqlite' in <c:\windows\system32>. I'm running Burp from my c:\temp folder with limited user rights.

**Comment by scottj** [comment]
In the default configuration, the sqlite file is created in the directory
where Burp is running from. Until we fix this issue, the workaround is to
start Burp from a directory where you have read/write permission. Once the
extension is successfully loaded, use the burp-hash tab to change the
location of the database file. At this point, you should be able to return
to running burp from your restricted directory.

**Comment by riramar** [comment]
Just noticed the same issue today using Burp Pro on Win10.
